apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment-01
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-deploy-01
  template:
    metadata:
      labels:
        app: my-deploy-01
    spec:
      containers:
      - name: pod
        image: rajesh072/movie-series-searching-app:latest
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: my-service-01
spec:
  selector:
    app: my-deploy-01
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 3000
      nodePort: 31110
  type: NodePort
